// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/appy.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/ledgers/index.tsx";
import * as $5 from "./routes/ledgers/new.tsx";
import * as $6 from "./routes/login.tsx";
import * as $7 from "./routes/schemas/index.tsx";
import * as $$0 from "./islands/Authenticate.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/Dropdown.tsx";
import * as $$3 from "./islands/LedgerName.tsx";
import * as $$4 from "./islands/Ledgers.tsx";
import * as $$5 from "./islands/Logout.tsx";
import * as $$6 from "./islands/Paste.tsx";
import * as $$7 from "./islands/Schema.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/appy.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/ledgers/index.tsx": $4,
    "./routes/ledgers/new.tsx": $5,
    "./routes/login.tsx": $6,
    "./routes/schemas/index.tsx": $7,
  },
  islands: {
    "./islands/Authenticate.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/Dropdown.tsx": $$2,
    "./islands/LedgerName.tsx": $$3,
    "./islands/Ledgers.tsx": $$4,
    "./islands/Logout.tsx": $$5,
    "./islands/Paste.tsx": $$6,
    "./islands/Schema.tsx": $$7,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
